- name: "Delete key pair"
  hosts: localhost
  tasks:
    - name: "Delete {{ key_pair_name_to_delete }} if it does not exist"
      include_role:
        name: "aws/ec2/key_pairs/delete_key_pair"
      vars:
        private_key_name_to_delete: "{{ key_pair_name_to_delete }}"
      when: key_pair_name_to_delete != ""
