name: Docker Image Build

on:
  push:
    branches:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set docker image tag
      id: get_info
      run: |
        if [[ "${{github.ref}}" == refs/pull/* ]]; then
          tag=${GITHUB_REF/\/merge/}
          echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
        else
          echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
        fi
        echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
        echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: hamdysimplyblock
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build & Push
      run: |
        SHORT_SHA=$(echo ${{ env.SHA }} | head -c 8)

        docker build --no-cache -t simplyblock/simplyblock -f docker/Dockerfile .

        docker tag simplyblock/simplyblock:latest simplyblock/simplyblock:$TAG
        docker tag simplyblock/simplyblock:latest simplyblock/simplyblock:$TAG-$SHORT_SHA

        docker push simplyblock/simplyblock:$TAG
        docker push simplyblock/simplyblock:$TAG-$SHORT_SHA

        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker tag simplyblock/simplyblock:$TAG simplyblock/simplyblock:dev
          docker push simplyblock/simplyblock:dev
        fi
